version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: sign_db
      POSTGRES_USER: sign_user
      POSTGRES_PASSWORD: sign_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_app_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: default
    command: ["java", "-jar", "app.jar"]

volumes:
  postgres_data: