spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sign_db
    username: sign_user
    password: sign_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
