spring:
  datasource:
    url: jdbc:postgresql://db:5432/sign_db
    username: sign_user
    password: sign_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret: your-super-secret-jwt-key

ai:
  url: http://ai:8000  # ✅ FastAPI 연동용